### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by genesofeve** [genesofeve/projectR#3]
Error in parse(outFile) : 
  /private/var/folders/w9/jnjcsn7d4s5gmzrgvzwdnnsc0000gn/T/RtmpqamsIo/devtools8bb269d6461/genesofeve-projectR-252df70/R/project:26:83: unexpected ','
25: 
26: setGeneric("projectR", function(data,AnnotionObj,IDcol,Patterns,NP,full, model=NA),
                                                                                      ^
ERROR: unable to collate and parse R files for package ‘projectR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/projectR’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/projectR’
Installation failed: Command failed (1)
> githubinstall("projectR")
Select a number or, hit 0 to cancel.

**Comment by ttriche** [comment]
pull request #4 fixes this, and passes Travis CI checks.  That said, there are deeper issues that will eventually need to be resolved.  Hopefully a successful install will be helpful in debugging those.
